name: 'Composite action'
description: 'Composite action'
runs:
  using: 'composite'
  steps:
    - run: echo 'FOO=bar' >> "$GITHUB_ENV"
      shell: bash
    - run: echo 'foo=${{ env.FOO }}'
      shell: bash
