name: Test

on:
  push:
    branches:
      - main
      
jobs:
  foo:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(steps.foo.outputs.matrix) }}
    steps:
      - run: echo '${{ github.event.repository }}'
      - id: foo
        run: echo "matrix=[{"os":\"ubuntu-latest\"},{"os":\"macos-latest\"}]" >> "$GITHUB_OUTPUT"
  
  bar:
    needs: [foo]
    
    strategy:
      matrix:
        include: ${{ fromJSON(needs.foo.outputs.matrix) }}
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Hello
        run: echo "Hello from ${{ matrix.os }}"
