name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  foo:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.foo.outputs.matrix }}
    steps:
      - run: node --version
    
      - name: Event
        run: echo '${{ toJSON(github.event) }}'

      - id: foo
        run: echo "matrix=[{"os":\"ubuntu-latest\"},{"os":\"macos-latest\"}]" >> "$GITHUB_OUTPUT"
  
  bar:
    needs: [foo]
    
    strategy:
      matrix:
        include: ${{ fromJSON(needs.foo.outputs.matrix) }}
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Hello
        run: echo "Hello from ${{ matrix.os }}"
